### ISSUE TITLE
DriverBaseAdapter.GetService throw NotImplementedException

### ISSUE THREAD

**Issue by FrancoisDenisCSL** [Tom-Lu/IVI.C.NET.Adapter#2]
Hi,
What should be implemented in this method ?
It is called at the end of the IviDcPwr.create of Driver QL-P from TTi (IVI-C) : QL355TP power supply.
seems to cause the method to return null.
Kind regards

**Comment by Tom-Lu** [comment]
I have implemented the GetService method to return current driver instance. Please try it out and let me know the result.
